#!/bin/sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

echo "Loadead script addition"

yabai -m config \
  external_bar off:40:0 \
  menubar_opacity 1.0 \
  mouse_follows_focus off \
  focus_follows_mouse off \
  display_arrangement_order default \
  window_origin_display default \
  window_placement second_child \
  window_insertion_point focused \
  window_zoom_persist on \
  window_shadow off \
  window_animation_duration 0.0 \
  window_animation_easing ease_out_circ \
  window_opacity_duration 0.0 \
  active_window_opacity 0.9 \
  normal_window_opacity 0.9 \
  window_opacity off \
  insert_feedback_color 0xffd75f5f \
  split_ratio 0.50 \
  split_type auto \
  auto_balance off \
  layout stack \
  mouse_modifier fn \
  mouse_action1 move \
  mouse_action2 resize \
  top_padding 04 \
  bottom_padding 04 \
  left_padding 04 \
  right_padding 04 \
  window_gap 02 \
  mouse_drop_action stack

# debug info, run yabai in terminal to see logs
~/.config/yabai/debug.nu
~/.config/yabai/setup.nu
~/.config/yabai/rules.nu

# auto switch focus to next window
yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows id,scratchpad,is-minimized --space | jq -re 'map(select(.scratchpad == \"\" and .\"is-minimized\" == false))' | jq -r '.[0].id') &> /dev/null"
yabai -m signal --add event=window_minimized active=yes action="if \$(yabai -m query --windows --window \$YABAI_WINDOW_ID | jq -r '.\"is-floating\"'); then yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows id,scratchpad,is-minimized --space | jq -re 'map(select(.scratchpad == \"\" and .\"is-minimized\" == false))' | jq -r '.[0].id') &> /dev/null; fi"

# yabai -m signal --add event=window_focused action="nu ~/.config/yabai/smart_stack.nu"
# yabai -m signal --add event=window_focused action="nu ~/.config/yabai/show_window.nu"
yabai -m signal --add event=window_created action="nu ~/.config/yabai/new_window.nu"
yabai -m signal --add event=window_created action="nu ~/.config/yabai/arc_windows.nu"
yabai -m signal --add event=window_resized action="nu ~/.config/yabai/arc_pip.nu"

yabai -m rule --apply
~/.config/yabai/arc_windows.nu

# enable only for bsp?
# borders active_color=0xff0077bc inactive_color=0x00000000 width=2.0 &
