git:
  paging:
    colorArg: always
    # pager: delta --dark --paging=never
    # pager: delta --dark --paging=never --syntax-theme base16-256 --diff-so-fancy
    externalDiffCommand: difft --color=always --display=side-by-side --syntax-highlight=off
    # externalDiffCommand: difft --color=always --display=inline
# colorArg: always
# pager: diff-so-fancy
# gui:
#   sidePanelWidth: 0.2

os:
  editPreset: "nvim-remote"
gui:
  theme:
    activeBorderColor:
      - "#f2cdcd"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#f2cdcd"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"

  authorColors:
    "*": "#b4befe"
