[mgr]

prepend_keymap = [
  { on = "<Backspace>", run = "leave", desc = "Back to the parent directory" },
  { on = "<Enter>", run = "enter", desc = "Enter the child directory" },
  { on = "<C-b>", run = "back", desc = "Back to previous directory" },
  { on = "<C-f>", run = "forward", desc = "Forward to next directory" },

  { on = "<S-Up>", run = "seek -5", desc = "Seek up 5 units in the preview" },
  { on = "<S-Down>", run = "seek 5", desc = "Seek down 5 units in the preview" },

]
