[user]
name = "niba"
email = "kamil.nibisz@gmail.com"

[ui]
conflict-marker-style = "git"
merge-editor = "vscode"
diff-formatter = ["difft", "--color=always", "$left", "$right"]
default-command = "log"
pager = { command = ["less", "-FRX"], env = { LESSCHARSET = "utf-8" } }

[revset-aliases]
'closest_bookmark(to)' = 'heads(::to & bookmarks())'

[aliases]
tug = ["bookmark", "move", "--from", "closest_bookmark(@-)", "--to", "@-"]
rebase-all = ["rebase", "-s", "all:roots(mutable())", "-d", "trunk()"]

[templates]
log_node = '''
if(self && !current_working_copy && !immutable && !conflict && in_branch(self),
"◇",
builtin_log_node
)
'''

[template-aliases]
"in_branch(commit)" = 'commit.contained_in("immutable_heads()..bookmarks()")'

[colors]
"diff token" = { underline = false }
